services:
  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:25.0.2
    command: "start-dev"
    environment:
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: keycloak
    volumes:
      - keycloak-data:/opt/keycloak/data
    ports:
      - 9025:8080
    networks:
      - keycloak-network
    restart: unless-stopped

networks:
  keycloak-network:
    driver: bridge

volumes:
  keycloak-data: